# Generated by Django 3.1.1 on 2020-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='state',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidding_price',
            field=models.IntegerField(default=0),
        ),
    ]
