# Generated by Django 3.1.1 on 2020-11-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201110_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_image', to='auctions.listing')),
            ],
        ),
    ]
