# Generated by Django 3.1.1 on 2020-11-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
