# Generated by Django 3.1.1 on 2020-11-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[("('a', 'Antique')", 'Antique'), ("('b', 'Electronic')", 'Electric'), ("('c', 'Home')", 'Home'), ("('d', 'Toys')", 'Toys'), ("('e', 'Education')", 'Education'), ("('f', 'Clothes')", 'Clothes'), ("('g', 'Workout')", 'Workout'), ("('h', 'Fashion')", 'Fashion'), ("('i', 'Food')", 'Food'), ('j', 'Luxury')], max_length=50),
        ),
    ]
