# Generated by Django 3.1.1 on 2020-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201113_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Antique'), ('b', 'Electronic'), ('c', 'Home'), ('d', 'Toys'), ('e', 'Education'), ('f', 'Clothes'), ('g', 'Workout'), ('h', 'Fashion'), ('i', 'Food'), ('j', 'Luxury')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
