# Generated by Django 3.1.1 on 2020-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Antique'), ('b', 'Electronic'), ('c', 'Home'), ('d', 'Toys'), ('e', 'Education'), ('f', 'Clothes'), ('g', 'Workout'), ('h', 'Fashion'), ('i', 'Food'), ('j', 'Luxury')], default='true', max_length=50),
        ),
    ]
